services:
  seed:
    image: web
    depends_on:
      - postgresql-db
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 8081:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    deploy:
      resources:
        limits:
          memory: 3G

  app:
    image: web
    depends_on:
      - postgresql-db
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 8080:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    deploy:
      resources:
        limits:
          memory: 500M

  postgresql-db:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_DB: master
      POSTGRES_PASSWORD: SuperSecret!
    deploy:
      resources:
        limits:
          cpus: 6
